### PR TITLE
Fixed aspect ratio in HDMI Vert mode

### PR DESCRIPTION
**Pull request by MrX-8B**

### CODE REVIEW

**Comment by sorgelig** [comment]
Text in this arcade has higher resolution than arcade resolution. That's why it uses 12MHz for CE.
If you switch to 6MHz, then you will see the text is garbled.

**Comment by sorgelig** [comment]
Btw, Aspect ratio on HDMI output is set by ARX/ARY. It doesn't depend on pixel clock and horizontal/vertical pixel amounts.

**Comment by MrX-8B** [comment]
Did you actually see it working?

**Comment by sorgelig** [comment]
I will check. I just remember why i've used 12MHz instead of original 6MHz pixel clock.
From your patch i see you lowered the resolution. But as i've told resolution doesn't affect the aspect ratio at all.

**Comment by MrX-8B** [comment]
Send a comparison image of the actual screen.
please wait.

**Comment by sorgelig** [comment]
Ok, i've tested. Aspect ratio was fixed by Alan. It's just not release yet. With new framework text is not garbled with lower resolution, so your tweak works ok.
btw, Aspect ratio is set here:
```
assign HDMI_ARX = status[1] ? 8'd16 : status[2] ? 8'd4 : 8'd3;
assign HDMI_ARY = status[1] ? 8'd9  : status[2] ? 8'd3 : 8'd4;
```
it's independent from resolution.

**Comment by MrX-8B** [comment]
> it's independent from resolution.

I understood.
Thank you for merge this request.

**Pull request merged**
